/* DO NOT EDIT THIS FILE
 * - vm.h (KAIA VM)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Jan 2022
 */
#ifndef VM_H
#define VM_H

// Globals
extern int debug_mode; 

#endif
