/* DO NOT EDIT THIS FILE
 * - vm_cs.h (KAIA VM)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Jan 2022
 */
#ifndef VM_CS_H
#define VM_CS_H

#include <pthread.h>
#include "vm_process.h"
#include "vm_schedule.h"

// Globals
extern pthread_cond_t cs_cv;
extern pthread_condattr_t cs_cvattr;
extern pthread_mutex_t cs_cv_m;

// Prototypes
void initialize_cs_system();
void cs_cleanup();
void *cs_thread(void *args);
void cs_schedule_process(process_data_t *proc);
void cs_schedule_terminate(pid_t pid, int exit_code);
void cs_suspend(pid_t pid);
void cs_resume(pid_t pid);
void cs_exiting_process(int exit_code);
void print_schedule();
void print_schedule_queue(queue_header_t *queue);
void print_process_node(process_node_t *node);
void start_cs();
void stop_cs();
void toggle_cs();
void print_cs_status();
void set_run_usec(useconds_t time);
void set_between_usec(useconds_t time);
#endif
