/* DO NOT EDIT THIS FILE
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Jan 2022
 */

#ifndef VM_SHELL_H
#define VM_SHELL_H

extern int debug_mode;
void shell(); // Run the Virtual System with Shell Access

#endif
