/* DO NOT EDIT THIS FILE
 * - vm_support.h (KAIA VM)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Jan 2022
 */

#ifndef VM_SUPPORT_H
#define VM_SUPPORT_H

#include "vm_schedule.h"

void register_signal(int sig, void (*handler)(int));
void print_prompt();
void print_status(char *msg);
void print_debug(char *msg);
void print_warning(char *msg);
void abort_error(char *msg, char *src);
void print_kaia_banner();
void print_schedule_debug(schedule_header_t *schedule);
void print_schedule_queue_debug(queue_header_t *queue);
void print_process_node_debug(process_node_t *node);

#endif
