/* DO NOT EDIT THIS FILE
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Jan 2022
 */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <sys/types.h>

#define SLEEP_USEC 500000 // 1000 = 1ms, 1000000 = 1sec
#define ITERATIONS 10 // Number of times to print

int main(int argc, char *argv[]){
  char *pic[] = {
"                          _____                          ",
"                   _.+sd$$$$$$$$$bs+._                   ",
"               .+d$$$$$$$$$$$$$$$$$$$$$b+.               ",
"            .sd$$$$$$$P^*^T$$$P^*`*^T$$$$$bs.            ",
"          .s$$$$$$$$P*     `*' _._  `T$$$$$$$s.          ",
"        .s$$$$$$$$$P          ` :$;   T$$$$$$$$s.        ",
"       s$$$$$$$$$$;  db..+s.   `**'    T$$$$$$$$$s       ",
"     .$$$$$$$$$$$$'  `T$P*'             T$$$$$$$$$$.     ",
"    .$$$$$$$$$$$$P                       T$$$$$$$$$$.    ",
"   .$$$$$$$$$$$$$b                       `$$$$$$$$$$$.   ",
"  :$$$$$$$$$$$$$$$.                       T$$$$$$$$$$$;  ",
"  $$$$$$$$$P^*' :$$b.                     d$$$$$$$$$$$$  ",
" :$$$$$$$P'      T$$$$bs._               :P'`*^T$$$$$$$; ",
" $$$$$$$P         `*T$$$$$b              '      `T$$$$$$ ",
":$$$$$$$b            `*T$$$s                      :$$$$$;",
":$$$$$$$$b.                                        $$$$$;",
"$$$$$$$$$$$b.                                     :$$$$$$",
"$$$$$$$$$$$$$bs.                                 .$$$$$$$",
"$$$$$$$$$$$$$$$$$bs.                           .d$$$$$$$$",
":$$$$$$$$$$$$$P*`*T$$bs,._                  .sd$$$$$$$$$;",
":$$$$$$$$$$$$P     TP^**T$bss++.._____..++sd$$$$$$$$$$$$;",
" $$$$$$$$$$$$b           `T$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ ",
" :$$$$$$$$$$$$b.           `*T$$P^*`*`*^^*T$$$$$$$$$$$$; ",
"  $$$b       `T$b+                        :$$$$$$$BUG$$  ",
"  :$P'         ``'               ,._.     ;$$$$$$$$$$$;  ",
"   `                            `*TP*     d$$P*******$   ",
"    `                                    :$$P'      /    ",
"     `                                  :dP'       /     ",
"      `.                               d$P       .'      ",
"[bug]   `.                             `'      .'        ",
"          `-.                               .-'          ",
"             `-.                         .-'             ",
"                `*+-._             _.-+*'                ",
"                      ``*-------*`'                      ",
"https://www.asciiart.eu/computers/linux Designed by bug"
}; //https://asciiartist.com/respect-ascii-artists-campaign/

  int i = 0;
  for(i = 0; i < 34; i++) {
    printf("%s\n", pic[i]);
    usleep(SLEEP_USEC);
  }
  
  return 0;
}
